spring.application.name=rkfund
server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/rkfund}
server.error.include-message=always
springdoc.swagger-ui.path=/swagger-ui.html
app.admin.email=${ADMIN_EMAIL:admin@rkfund.com}
app.admin.password=${ADMIN_PASSWORD:ChangeMe123!}
app.auth.dev-otp=${DEV_OTP:}
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=26MB
